# Site settings
title: DAU-BigDataTeam(동아대 빅데이터팀)
description: "Donga Univ Computer AI Engineering BigDataTeam"
url: "https://bigdatateam.net" # Actual base url of the website
baseurl: "/"           # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Jeonghyeon Park"
  email: "jhparkinglot@gmail.com"
  url: "https://jhpark.org"
permalink: /:title:output_ext # /:year/:month/:day

#Plugins
plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]

#Pagination
paginate: 20
paginate_path: "/page:num/"

#SEO
twitter:
  username: 
  card: summary
facebook:
  app_id: # Facebook app ID for Facebook insights
  publisher: # Facebook page URL or ID of the publishing entity
  admins: # Facebook user ID for domain insights linked to a personal account
logo: /assets/img/logo.jpg
social:
  links: #List your social links here
    - https://twitter.com/uesername
    - https://www.github.com/jhparkland
    - https://www.linkedin.com/in/uesername/

webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
lang: en_US

#Highlighter
kramdown:
  input:          GFM
  syntax_highlighter: rouge 

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: False
    block:
      line_numbers: False
      start_line: 1

#Sass
sass:
  style: compressed
  sourcemap: never

# Analytics
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-Z438CCPYGJ "
    anonymize_ip         : false 


