# Site settings
title: DAU-BigDataTeam
description: "Donga Univ Computer AI Engineering BigDataTeam"
url:  "https://dau-bigdatateams.github.io" # Actual base url of the website
baseurl: "/"           # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Jeonghyeon Park"
  email: "jhparkinglot@gmail.com"
  url: "https://jhpark.org"
permalink: /:year/:month/:day/:title:output_ext

#Plugins
plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]

#Pagination
paginate: 5
paginate_path: "/page:num/"

#SEO
twitter:
  username: pandasekh
  card: summary
facebook:
  app_id: # Facebook app ID for Facebook insights
  publisher: # Facebook page URL or ID of the publishing entity
  admins: # Facebook user ID for domain insights linked to a personal account
logo: /assets/img/logo.jpg
social:
  links: #List your social links here
    - https://twitter.com/PandaSekh
    - https://www.github.com/pandasekh
    - https://www.linkedin.com/in/alessio-franceschi/
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
lang: en_US

#Highlighter
kramdown:
  input:          GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: False
    block:
      line_numbers: True
      start_line: 1

#Sass
sass:
  style: compressed
  sourcemap: never